### ISSUE TITLE
HTTP_AUTHORIZATION Stripped Out in AWS ElasticBeanstalk Deployments

### ISSUE THREAD

**Issue by ScottHull** [florimondmanca/djangorestframework-api-key#74]
I'm running an ElasticBeanstalk environment and spent hours trying to figure out why my API keys were not working in my deployed environments.  Turns out that HTTP_AUTHORIZATION headers were being stripped out.  Following a solution posted on the AWS forms, the header passes when you include a file with these contents in `.ebextensions`:

```
files:
  "/etc/httpd/conf.d/wsgihacks.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      WSGIPassAuthorization On
```

So you have to do some WSGI configuring to get it working.  Not a bug, just thought that this would be helpful information to have here, or possibly in the documentation.
